apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-nginx-pvc
  namespace: site
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 50Mi