apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-site-pv
  labels:
    name: nginx-site-pv
  namespace: site
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.122.40 
    path: "/srv/nfs/data" 