apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-site
  namespace: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      volumes:
      - name: site-nginx-html
        persistentVolumeClaim:
          claimName: site-nginx-pvc
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: site-nginx-html 
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "250m"